version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
    groups:
      postcss:
        patterns:
          - "postcss*"
      stylelint:
        patterns:
          - "stylelint*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
