name: CI

env:
  NODE_VERSION: "22"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Prettier
        run: yarn prettier . --check
      - name: Stylelint
        run: yarn run stylelint
      - name: build
        run: yarn build
